name: Daily Commit Workflow

on:
  schedule:
    - cron: '17 5 * * *'  # Runs every day at 05:17 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Add commit for 23f1002420@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily_log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "Daily update: $(date)" || echo "No changes to commit"
          git push
